In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('wine.data', header=None)

In [3]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [4]:
y = df[0]
X = df.drop([0], axis=1)

In [5]:
X

,1,2,3,4,5,6,7,8,9,10,11,12,13
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [6]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64

In [7]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.utils import shuffle
from sklearn.preprocessing import scale

In [8]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
# X, y = shuffle(X, y, random_state=42)
result = []
for n in range (1, 50):
    clf = KNeighborsClassifier(n_neighbors=n)
    scores = cross_val_score(clf, X, y, cv=kf)
    result.append(scores.mean())
    print(n, scores, scores.mean())
print('max score without *scale* : score = {}, N = {}'.format(
    result[np.argmax(result)], 
    np.argmax(result) + 1))

1 [0.77777778 0.66666667 0.72222222 0.71428571 0.77142857] 0.7304761904761905
2 [0.72222222 0.63888889 0.69444444 0.57142857 0.68571429] 0.6625396825396825
3 [0.80555556 0.61111111 0.63888889 0.65714286 0.82857143] 0.7082539682539682
4 [0.75       0.52777778 0.61111111 0.65714286 0.74285714] 0.6577777777777778
5 [0.72222222 0.61111111 0.61111111 0.68571429 0.74285714] 0.6746031746031746
6 [0.72222222 0.63888889 0.63888889 0.68571429 0.68571429] 0.6742857142857144
7 [0.69444444 0.58333333 0.72222222 0.68571429 0.71428571] 0.68
8 [0.72222222 0.61111111 0.66666667 0.65714286 0.74285714] 0.6799999999999999
9 [0.72222222 0.63888889 0.72222222 0.68571429 0.74285714] 0.7023809523809523
10 [0.72222222 0.61111111 0.63888889 0.68571429 0.74285714] 0.6801587301587302
11 [0.75       0.63888889 0.66666667 0.71428571 0.74285714] 0.7025396825396826
12 [0.72222222 0.66666667 0.69444444 0.68571429 0.71428571] 0.6966666666666667
13 [0.72222222 0.69444444 0.66666667 0.65714286 0.71428571] 0.6909523809523809
14 [0.72222222 0.66666667 0.72222222 0.6        0.68571429] 0.6793650793650794
15 [0.75       0.72222222 0.69444444 0.62857143 0.71428571] 0.701904761904762
16 [0.72222222 0.63888889 0.72222222 0.6        0.71428571] 0.6795238095238096
17 [0.77777778 0.72222222 0.72222222 0.6        0.68571429] 0.7015873015873015
18 [0.77777778 0.61111111 0.69444444 0.6        0.71428571] 0.6795238095238095
19 [0.77777778 0.63888889 0.69444444 0.6        0.68571429] 0.6793650793650793
20 [0.77777778 0.61111111 0.69444444 0.62857143 0.74285714] 0.6909523809523809
21 [0.77777778 0.63888889 0.75       0.62857143 0.71428571] 0.7019047619047619
22 [0.77777778 0.63888889 0.69444444 0.62857143 0.74285714] 0.6965079365079364
23 [0.77777778 0.63888889 0.72222222 0.6        0.77142857] 0.7020634920634921
24 [0.77777778 0.63888889 0.75       0.62857143 0.74285714] 0.7076190476190476
25 [0.77777778 0.63888889 0.75       0.62857143 0.71428571] 0.7019047619047619
26 [0.77777778 0.61111111 0.72222222 0.65714286 0.71428571] 0.6965079365079365
27 [0.77777778 0.63888889 0.72222222 0.62857143 0.71428571] 0.6963492063492064
28 [0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
29 [0.77777778 0.63888889 0.72222222 0.68571429 0.74285714] 0.7134920634920634
30 [0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
31 [0.77777778 0.58333333 0.72222222 0.62857143 0.74285714] 0.690952380952381
32 [0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
33 [0.77777778 0.61111111 0.75       0.68571429 0.74285714] 0.7134920634920634
34 [0.83333333 0.61111111 0.75       0.68571429 0.74285714] 0.7246031746031747
35 [0.80555556 0.66666667 0.72222222 0.68571429 0.74285714] 0.7246031746031747
36 [0.83333333 0.61111111 0.69444444 0.68571429 0.74285714] 0.7134920634920636
37 [0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
38 [0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
39 [0.77777778 0.61111111 0.72222222 0.68571429 0.74285714] 0.7079365079365079
40 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
41 [0.80555556 0.61111111 0.72222222 0.68571429 0.74285714] 0.7134920634920634
42 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
43 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
44 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
45 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
46 [0.80555556 0.61111111 0.72222222 0.68571429 0.71428571] 0.7077777777777777
47 [0.75       0.61111111 0.72222222 0.68571429 0.71428571] 0.6966666666666667
48 [0.83333333 0.61111111 0.72222222 0.71428571 0.71428571] 0.7190476190476192
49 [0.75       0.61111111 0.72222222 0.68571429 0.71428571] 0.6966666666666667
max score without *scale* : score = 0.7304761904761905, N = 1

In [9]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
X1 = scale(X)
result1 = []
for n in range (1, 50):
    clf = KNeighborsClassifier(n_neighbors=n)
    scores = cross_val_score(clf, X1, y, cv=kf)
    result1.append(scores.mean())
    print(n, scores, scores.mean())
print('max score with *scale* : score = {}, N = {}'.format(
    result1[np.argmax(result1)], 
    np.argmax(result1) + 1))

1 [0.94444444 0.94444444 0.91666667 0.97142857 0.94285714] 0.943968253968254
2 [0.94444444 0.88888889 0.91666667 0.97142857 0.94285714] 0.9328571428571429
3 [0.94444444 0.94444444 0.97222222 0.97142857 0.94285714] 0.9550793650793651
4 [0.94444444 0.91666667 0.94444444 0.94285714 0.94285714] 0.9382539682539683
5 [0.94444444 0.94444444 0.97222222 0.91428571 0.97142857] 0.9493650793650794
6 [0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095
7 [0.94444444 0.91666667 0.97222222 0.94285714 0.97142857] 0.9495238095238095
8 [0.94444444 0.91666667 0.97222222 0.97142857 0.97142857] 0.9552380952380952
9 [0.94444444 0.94444444 0.97222222 0.94285714 1.        ] 0.9607936507936508
10 [0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508
11 [0.94444444 0.94444444 0.94444444 0.97142857 1.        ] 0.9609523809523809
12 [0.97222222 0.91666667 0.94444444 0.97142857 0.97142857] 0.9552380952380952
13 [0.94444444 0.94444444 0.94444444 0.91428571 1.        ] 0.9495238095238093
14 [0.97222222 0.94444444 0.97222222 0.97142857 0.97142857] 0.9663492063492063
15 [0.97222222 0.94444444 0.97222222 0.97142857 1.        ] 0.9720634920634922
16 [0.97222222 0.94444444 0.97222222 0.97142857 1.        ] 0.9720634920634922
17 [0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364
18 [0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364
19 [0.94444444 0.91666667 0.94444444 0.97142857 1.        ] 0.9553968253968254
20 [0.97222222 0.91666667 0.97222222 0.97142857 1.        ] 0.9665079365079364
21 [0.94444444 0.91666667 0.97222222 0.97142857 1.        ] 0.9609523809523811
22 [0.94444444 0.94444444 0.97222222 0.97142857 1.        ] 0.9665079365079364
23 [0.94444444 0.94444444 0.94444444 0.97142857 1.        ] 0.9609523809523809
24 [0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952
25 [0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952
26 [0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508
27 [0.94444444 0.94444444 0.94444444 0.97142857 0.97142857] 0.9552380952380952
28 [0.97222222 0.94444444 0.97222222 0.97142857 0.97142857] 0.9663492063492063
29 [1.         0.94444444 0.97222222 0.97142857 1.        ] 0.9776190476190475
30 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
31 [0.97222222 0.91666667 0.94444444 0.97142857 0.97142857] 0.9552380952380952
32 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
33 [1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063
34 [1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063
35 [1.         0.88888889 0.97222222 0.97142857 0.97142857] 0.9607936507936508
36 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
37 [0.97222222 0.88888889 0.97222222 0.97142857 0.97142857] 0.9552380952380952
38 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
39 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
40 [0.97222222 0.91666667 0.97222222 0.97142857 0.97142857] 0.9607936507936508
41 [1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063
42 [0.94444444 0.94444444 0.97222222 0.97142857 0.97142857] 0.9607936507936508
43 [1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063
44 [1.         0.91666667 0.97222222 0.97142857 0.94285714] 0.9606349206349206
45 [1.         0.91666667 0.97222222 0.97142857 0.97142857] 0.9663492063492063
46 [0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095
47 [0.97222222 0.91666667 0.97222222 0.97142857 0.94285714] 0.9550793650793651
48 [0.94444444 0.91666667 0.97222222 0.97142857 0.94285714] 0.9495238095238095
49 [0.97222222 0.91666667 0.97222222 0.97142857 0.94285714] 0.9550793650793651
max score with *scale* : score = 0.9776190476190475, N = 29

In [10]:
def toFixed(numObj, digits=0):
    return f"{numObj:.{digits}f}"

In [11]:
with open('q1_bestN', 'w') as f:
    f.write(str(np.argmax(result) + 1))

In [12]:
with open('q2_score_bestN', 'w') as f:
    f.write(str(toFixed(result[np.argmax(result)], 2)))

In [13]:
with open('q3_bestN_scale', 'w') as f:
    f.write(str(np.argmax(result1) + 1))

In [14]:
with open('q4_score_bestN_scale', 'w') as f:
    f.write(str(toFixed(result1[np.argmax(result1)], 2)))